### ISSUE TITLE
 No module named 'PIL'

### ISSUE THREAD

**Issue by hobolyra** [torresflo/Tag-Machine#1]
All requirements and modules have been installed in a separate environment, but when I finally run this it spits out the following issue: (folder chain replaced with stars, but contains no spaces in titles)

```
Traceback (most recent call last):
  File "C:\****\metadata_tagger\main.py", line 4, in <module>
    from UI.MainWindow import MainWindow
  File "C:\****\metadata_tagger\UI\MainWindow.py", line 2, in <module>
    from UI.PredictionItemModel import PredictionItemModel
  File "C:\****\metadata_tagger\UI\PredictionItemModel.py", line 2, in <module>
    from PIL.ImageQt import ImageQt
ModuleNotFoundError: No module named 'PIL'
```

**Comment by hobolyra** [comment]
Oh, seems that this also needs Pillow, and the requirement isn't in the text file or this Git page. Issue fixed with a simple install of Pillow into the environment

**Comment by torresflo** [comment]
Sorry for that. I will update the readme file of this project. Thanks for letting me know!
